export const CAR_MAKES: Record<string, string[]> = {
  "Alfa Romeo": ["Giulia", "Stelvio", "Giulietta", "159", "Spider"],
  Audi: ["A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron", "TT", "RS3", "RS6"],
  Aito: ["M5", "M7", "M9"],
  Aion: ["S", "Y", "V", "LX", "GT"],
  Baojun: ["510", "530", "RS-3", "RS-5", "Valli", "310", "KiWi EV"],
  BMW: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "iX", "M3", "M4", "M5"],
  BYD: ["Atto 3", "Seal", "Dolphin", "Han", "Tang", "Song Plus"],
  Cadillac: ["Escalade", "CT5", "CT6", "XT5", "XT6", "SRX"],
  Chery: ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo 5", "Arrizo 8"],
  Chevrolet: ["Malibu", "Cruze", "Aveo", "Spark", "Traverse", "Equinox", "Tahoe", "Suburban", "Camaro", "Trailblazer", "Niva"],
  Changan: ["CS35", "CS55", "CS75", "CS85", "UNI-T", "UNI-K", "UNI-V", "Alsvin", "Eado", "Raeton", "Hunter", "Lumin", "E-Rock"],
  Chrysler: ["300", "Pacifica", "Grand Voyager"],
  Citroën: ["C3", "C4", "C5", "C5 Aircross", "Berlingo", "C4 Picasso"],
  Dacia: ["Logan", "Sandero", "Duster", "Jogger", "Spring"],
  Daewoo: ["Matiz", "Nexia", "Lanos", "Leganza", "Kalos", "Espero"],
  Deepal: ["S7", "SL03", "G318"],
  Dodge: ["Charger", "Challenger", "Durango", "Ram", "Journey"],
  Dongfeng: ["580", "SX6", "S560", "370", "E70", "Glory 680"],
  Exeed: ["LX", "TXL", "VX", "RX", "Sterra"],
  Fiat: ["500", "Punto", "Doblo", "Ducato", "Panda", "Linea"],
  Ford: ["Focus", "Fiesta", "Mondeo", "Mustang", "Explorer", "Escape", "Ranger", "F-150", "Kuga", "Fusion", "Transit", "C-Max"],
  GAC: ["GS3", "GS4", "GS8", "M8", "GA6", "Empow", "Emkoo"],
  Geely: ["Emgrand", "Coolray", "Atlas", "Monjaro", "Tugella", "Azkarra"],
  GMC: ["Yukon", "Sierra", "Acadia", "Terrain", "Canyon"],
  Haval: ["Jolion", "Dargo", "F7", "H6", "H9", "M6", "Haval H3"],
  Honda: ["Accord", "Civic", "CR-V", "Pilot", "HR-V", "Fit", "Jazz", "City", "Odyssey", "Legend", "Prelude"],
  Hongqi: ["H5", "H6", "H9", "HS5", "HS7", "E-HS9"],
  Hyundai: ["Elantra", "Sonata", "Accent", "Solaris", "Creta", "Tucson", "Santa Fe", "Palisade", "Kona", "i30", "i10", "Staria", "Genesis"],
  Infiniti: ["Q50", "Q70", "QX50", "QX60", "QX80", "EX35", "FX37"],
  JAC: ["S3", "S4", "S5", "S7", "X8", "J7", "T6", "T8", "iEV7S", "E10X"],
  Jaecoo: ["J7", "J8"],
  Jaguar: ["XE", "XF", "XJ", "F-Type", "E-Pace", "F-Pace", "I-Pace"],
  Jeep: ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Renegade", "Gladiator", "Liberty"],
  Jetour: ["X50", "X70", "X70 Plus", "X90", "Dashing", "Traveler", "T2"],
  Kia: ["Rio", "Cerato", "K5", "Sportage", "Sorento", "Tucson", "Telluride", "Stinger", "Soul", "Picanto", "Ceed", "Mohave", "K9"],
  Lada: ["Granta", "Vesta", "Kalina", "Priora", "Niva", "Largus", "X-Ray"],
  "Land Rover": ["Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar", "Discovery", "Discovery Sport", "Defender"],
  Lexus: ["ES", "GS", "IS", "LS", "RX", "NX", "GX", "LX", "UX", "RC", "LC", "LM"],
  "Li Auto": ["L6", "L7", "L8", "L9", "MEGA"],
  Lifan: ["X50", "X60", "X70", "620", "720", "Maiwei"],
  Mazda: ["Mazda3", "Mazda6", "CX-3", "CX-5", "CX-7", "CX-9", "CX-30", "MX-5", "BT-50"],
  "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "CLS", "AMG GT", "V-Class", "EQC", "EQE", "EQS", "Sprinter"],
  MG: ["ZS", "HS", "RX5", "MG5", "MG6", "MG7", "Marvel R", "EZS"],
  Mini: ["Cooper", "Cooper S", "Countryman", "Clubman", "John Cooper Works"],
  Mitsubishi: ["Lancer", "Outlander", "Pajero", "L200", "ASX", "Eclipse Cross", "Mirage", "Galant"],
  Neta: ["V", "U", "S", "Aya", "X", "GT"],
  Nissan: ["Almera", "Sentra", "Teana", "Altima", "Qashqai", "X-Trail", "Pathfinder", "Navara", "Patrol", "Murano", "Juke", "GT-R", "Leaf", "Note"],
  NIO: ["ES6", "ES8", "EC6", "ET5", "ET7", "EL6"],
  Omoda: ["C5", "S5", "E5", "G7"],
  Opel: ["Astra", "Corsa", "Insignia", "Mokka", "Mokka X", "Antara", "Zafira", "Vectra", "Vivaro", "Meriva"],
  Ora: ["Good Cat", "Funky Cat", "Ballet Cat", "Lightning Cat", "03"],
  Peugeot: ["208", "308", "408", "508", "2008", "3008", "5008", "Partner", "Boxer", "Rifter"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster", "Cayman"],
  Renault: ["Logan", "Sandero", "Clio", "Megane", "Laguna", "Duster", "Kaptur", "Koleos", "Arkana", "Trafic", "Master", "Symbol"],
  Roewe: ["RX3", "RX5", "RX8", "i5", "Ei5", "D5X"],
  Seat: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Alhambra", "Toledo"],
  Skywell: ["ET3", "ET5", "HT3"],
  Škoda: ["Octavia", "Fabia", "Rapid", "Kodiaq", "Karoq", "Superb", "Yeti", "Scala", "Enyaq"],
  Subaru: ["Impreza", "WRX", "Legacy", "Outback", "Forester", "XV", "Ascent", "Crosstrek"],
  Suzuki: ["Swift", "Vitara", "SX4", "Jimny", "Grand Vitara", "Ignis", "Baleno", "Celerio"],
  Tank: ["300", "400", "500", "700", "800"],
  Tesla: ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
  Toyota: ["Camry", "Corolla", "RAV4", "Land Cruiser", "Land Cruiser Prado", "Highlander", "Avalon", "Yaris", "Yaris Cross", "C-HR", "Supra", "Tacoma", "Hilux", "Fortuner", "Sequoia", "Sienna", "Venza", "Alphard", "Mirai", "Hiace"],
  Volkswagen: ["Golf", "Passat", "Polo", "Jetta", "Tiguan", "Touareg", "Atlas", "Taos", "Arteon", "Beetle", "Amarok", "Multivan", "Caddy", "T-Cross", "T-Roc", "ID.4", "Scirocco"],
  Volvo: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "V40", "S40", "C40"],
  Voyah: ["Free", "Dreamer", "Passion", "Courage"],
  Wey: ["VV5", "VV6", "VV7", "Mocha", "Latte", "Coffee 01", "Coffee 02"],
  Wuling: ["Mini EV", "Air EV", "Bingo", "Xingchi", "Almaz", "Star"],
  Xiaomi: ["SU7", "SU7 Pro", "SU7 Max", "YU7"],
  Xpeng: ["G3", "G6", "G9", "P5", "P7", "P7i"],
  Zeekr: ["001", "003", "005", "007", "009", "X", "Mix"],
};

export const CAR_MAKES_LIST = Object.keys(CAR_MAKES).sort();

export function getCarModels(make: string): string[] {
  if (!make) return [];
  return CAR_MAKES[make] ?? [];
}
